In [2]:
import ipyparallel as ipp
import numpy as np
import pandas as pd

In [5]:
rc = ipp.Client()

In [6]:
rc.ids

[0, 1, 2, 3]

In [7]:
dview = rc[:]

In [8]:
dview.push(dict(a = 1.03232, b = 3453))

<AsyncResult: _push>

In [9]:
dict(a = 1.03232, b = 3453)

{'a': 1.03232, 'b': 3453}

In [11]:
dview.pull('a')

<AsyncResult: _pull>

In [14]:
ar = dview.pull('b', block=False)

In [15]:
ar.get()

[3453, 3453, 3453, 3453]

In [16]:
dview['a'] = ['foo','bar']

In [17]:
dview['a']

[['foo', 'bar'], ['foo', 'bar'], ['foo', 'bar'], ['foo', 'bar']]

In [18]:
dview.scatter('a',np.linspace(0,100))

<AsyncResult: scatter>

In [20]:
dview['a']

[array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531,  10.20408163,  12.24489796,  14.28571429,
         16.32653061,  18.36734694,  20.40816327,  22.44897959,  24.48979592]),
 array([ 26.53061224,  28.57142857,  30.6122449 ,  32.65306122,
         34.69387755,  36.73469388,  38.7755102 ,  40.81632653,
         42.85714286,  44.89795918,  46.93877551,  48.97959184,  51.02040816]),
 array([ 53.06122449,  55.10204082,  57.14285714,  59.18367347,
         61.2244898 ,  63.26530612,  65.30612245,  67.34693878,
         69.3877551 ,  71.42857143,  73.46938776,  75.51020408]),
 array([  77.55102041,   79.59183673,   81.63265306,   83.67346939,
          85.71428571,   87.75510204,   89.79591837,   91.83673469,
          93.87755102,   95.91836735,   97.95918367,  100.        ])]

In [28]:
df = pd.DataFrame({'a':np.linspace(0,100,100),'b':np.random.rand(100)})

In [33]:
dview.scatter('df',df)

<AsyncResult: scatter>

In [40]:
dview.scatter('x',range(64))

<AsyncResult: scatter>

In [41]:
dview['x']

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
 [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
 [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]

In [42]:
%px y = [i**10 for i in x]

In [44]:
y = dview.gather('y')

In [57]:
%px c = [t**3 for t in x]

In [84]:
@dview.remote(block=True) 
def res():
    return a

@dview.parallel(block=True) 
def res2(x):
    return x**2

In [85]:
res()

[array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531,  10.20408163,  12.24489796,  14.28571429,
         16.32653061,  18.36734694,  20.40816327,  22.44897959,  24.48979592]),
 array([ 26.53061224,  28.57142857,  30.6122449 ,  32.65306122,
         34.69387755,  36.73469388,  38.7755102 ,  40.81632653,
         42.85714286,  44.89795918,  46.93877551,  48.97959184,  51.02040816]),
 array([ 53.06122449,  55.10204082,  57.14285714,  59.18367347,
         61.2244898 ,  63.26530612,  65.30612245,  67.34693878,
         69.3877551 ,  71.42857143,  73.46938776,  75.51020408]),
 array([  77.55102041,   79.59183673,   81.63265306,   83.67346939,
          85.71428571,   87.75510204,   89.79591837,   91.83673469,
          93.87755102,   95.91836735,   97.95918367,  100.        ])]

In [63]:
f(4)

4

In [66]:
%px y = [f(i) for i in x]

CompositeError: one or more exceptions from call to method: execute
[0:execute]: NameError: name 'f' is not defined
[1:execute]: NameError: name 'f' is not defined
[2:execute]: NameError: name 'f' is not defined
[3:execute]: NameError: name 'f' is not defined